apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag-chatbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rag-chatbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    application: agentic-chatbot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rag-chatbot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      application: agentic-chatbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rag-chatbot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        application: agentic-chatbot
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "rag-chatbot.fullname" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: OPENSEARCH_ENDPOINT
              value: {{ .Values.aws.opensearch_endpoint }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
          ports:
            - name: http
              containerPort: 7860
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
