apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rag-chatbot.fullname" . }}-readonly
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - services
    - namespaces
    - nodes
  verbs:
    - get
    - list
    - watch
- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rag-chatbot.fullname" . }}-readonly-binding
subjects:
- kind: ServiceAccount
  name: {{ include "rag-chatbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "rag-chatbot.fullname" . }}-readonly
  apiGroup: rbac.authorization.k8s.io
