apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rag-chatbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rag-chatbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.aws.role }}
  {{- end }}