prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    ruleSelector:
      matchLabels:
        role: custom-rule

alertmanager:
 config:
   global:
     resolve_timeout: 5m
     slack_api_url: "${slack_webhook_url}"
   route:
     group_by: ['job']
     group_wait: 30s
     group_interval: 1m
     repeat_interval: 12h
     receiver: 'slack'
     routes:
     - match:
         alertname: DeadMansSwitch
       receiver: 'null'
     - match:
       receiver: 'slack'
       continue: true
   receivers:
   - name: 'null'
   - name: 'slack'
     slack_configs:
     - channel: "#${slack_channel_name}"
       send_resolved: true
       title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
       text: >-
         {{ range .Alerts }}
           *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
           *Description:* {{ .Annotations.description }}
           *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
           *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
           {{ end }}
         {{ end }}
