apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    release: kube-prometheus-stack
    role: custom-rule
  name: kube-pod-pending
  namespace: kube-prometheus-stack
spec:
  groups:
  - name: pod-demo-rules
    rules:
    - alert: PodPendingTooLong
      expr: sum by (namespace, pod) (kube_pod_status_phase{phase="Pending"}) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Kubernetes Pod Pending for more than 1 minute (Pod: {{ $labels.pod }})"
        description: |
          Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a pending state for over 1 minute.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}
  - name: OOMKillAlerts
    rules:
    - alert: ServiceBOOMKill
      expr: kube_pod_container_status_restarts_total{container="service-b"} > 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Service B Container OOMKilled"
        description: "Service B container has been restarted due to an out-of-memory condition."