replicaCount: 1

logLevel: "INFO"

image:
  repository: your-ecr-repo/chatbot
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 7860

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

aws:
  role: ""
  region: ""
  opensearch_endpoint: ""

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
